### ISSUE TITLE
Getting rid of node/gulp?

### ISSUE THREAD

**Issue by trickkiste** [jekyller/jasper2#101]
How can I get rid of node and gulp?
The added dependencies make deployment rather tedious.

**Comment by muratcorlu** [comment]
I think it'll be enough to just fix CSS urls in `default.html` and `404.html` by replacing `built` with `css` like:

```html
    <link rel="stylesheet" type="text/css" href="{{ site.baseurl }}assets/css/screen.css" />
    <link rel="stylesheet" type="text/css" href="{{ site.baseurl }}assets/css/screen.edited.css" />
    <link rel="stylesheet" type="text/css" href="{{ site.baseurl }}assets/css/syntax.css" />
```

**Comment by geotheory** [comment]
This is good but the footer disappears. Any idea why @muratcorlu

**Comment by muratcorlu** [comment]
TBH, I have no clue. This is a really old answer that even I’m not use this theme anymore.

Did you check which css rule is hiding footer?

**Comment by geotheory** [comment]
No worries. I'll see if I can identify the issue.
