### ISSUE TITLE
I can't find the location to add the javascript code for google analytics

### ISSUE THREAD

**Issue by bluebamus** [jekyller/jasper2#111]
Generally When we use google analytics service, It require identifier id and javascript code. but In this solution, I can't find how I can add javascript in any place. even I can't find it at _site folder too.
So I want to ask you. Is this google analytics working as well?

* I don't understand some config setting below that :

safe: False
lsi: False
username: devspoons
repo: devspoons.github.io
branch: master
relative_source: ../jasper2/
destination: _site/
production_url:  https://devspoons.github.io
source_url:  https://github.com/devspoons/devspoons.github.io

How can I understand each lines related process?
If you have manual for this, let's me know please.

and "exclude:" this line also, I want to understand.
is it ignored when it do building jekyll?

**Comment by biomadeira** [comment]
@bluebamus You can read more about the jekyll configuration here: https://jekyllrb.com/docs/configuration/options/
Regarding the google analytics,  you can modify the id here: https://github.com/jekyller/jasper2/blob/master/_config.yml#L33
