### ISSUE TITLE
Fix disqus error

### ISSUE THREAD

**Issue by HyeonsuRyu** [jekyller/jasper2#119]
I tried to apply disqus to the post, but there was an error.
The problem is /_layouts/post.html
I fixed this problem using the following methods.

origin code
this.page.url = '{{ site.url }}{{ page.url }}';
this.page.identifier ='{{ page.id }}';
this.page.title = '{{ page.title }}';
---------------------------------------------------
fixed code
var this_page_url = '{{ site.url }}{{ page.url }}';
var this_page_identifier = '{{ page.id }}';
var this_page_title = '{{ page.title }}';

**Comment by biomadeira** [comment]
Thanks @HyeonsuRyu! I will make the changes to the template!
