### ISSUE TITLE
Problems with Author's & Tag's pages

### ISSUE THREAD

**Issue by echofatalerror** [jekyller/jasper2#15]
I have problems with Author's & Tag's pages. When i visite one of this i get 404 page 😢

**Comment by biomadeira** [comment]
@echofatalerror is this happening when you run Jekyll locally or when you build your site with GitHub?

**Comment by techlanka** [comment]
Does anyone got a fix for this??? plss

**Comment by techlanka** [comment]
Found a fix.:D

**Comment by HenryCWong** [comment]
I seem to having a problem with the first option, building the site locally. I simply did a test of changing the name of Ghost to Nick. Nick shows up on articles, but I keep getting a 404 every time I click on "Nick"'s (an author's) name.
