### ISSUE TITLE
Code block syntax highlighting is not working

### ISSUE THREAD

**Issue by LoveqLRC** [jekyller/jasper2#21]
just like [demo](https://myjekyll.github.io/jasper2/a-full-and-comprehensive-style-test) show

**Comment by rahidelvi** [comment]
I'm having trouble with this too. In the demo I notice that the page demonstrating the syntax highlighting is an _html_ page, however I was working on a markdown file.

**Comment by jinh574** [comment]
I'm having trouble with this too.. I did write correctly on my markdown file. but it doesn't work

**Comment by rahidelvi** [comment]
I couldn't debug, so I went with an alternate approach. Instead of highlight.js, I used [prism.js](http://prismjs.com/) and that [worked for me](https://blog.rahidelvi.ca/battery-level-notifications-for-ubuntu#the-script).

**Comment by biomadeira** [comment]
Hi guys! I will have a look at this! Code highlights was working before but
Ghost's team keep changing their css for this and I didn't check the last time they changed it. Anyway I think I still need to sort things out, because I am mixing highlight.js with Casper's...

**Comment by LoveqLRC** [comment]
Hope to fix it

**Comment by biomadeira** [comment]
@rahidelvi and @LoveqLRC I think this https://github.com/myJekyll/jasper2/commit/7a4ab9cc59145912f12989b6c5d4c185dbe3e9cb and https://github.com/myJekyll/jasper2/commit/c1adbe36524967e5cd490fe2dd2f89ad7ab91f9f helped as it now looks like Ghost's, but there is no actual syntax highlight. I will try with http://prismjs.com/ later on...

Thank you!
F:)

**Comment by thepulkitagarwal** [comment]
According to https://jekyllrb.com/docs/templates/#stylesheets-for-syntax-highlighting , an additional stylesheet [syntax.css](https://github.com/mojombo/tpw/tree/master/css/syntax.css) needs to be included:

> In order for the highlighting to show up, you’ll need to include a highlighting stylesheet. For an example stylesheet you can look at syntax.css. These are the same styles as used by GitHub and you are free to use them for your own site. If you use linenos, you might want to include an additional CSS class definition for the .lineno class in syntax.css to distinguish the line numbers from the highlighted code.

This fixed the issue for me.

**Comment by jinh574** [comment]
Still hope to fix it
