### ISSUE TITLE
Markup shows on next related post

### ISSUE THREAD

**Issue by rahidelvi** [jekyller/jasper2#24]
The card that shows the _next_ post always shows markup. I'm noticing that the `strip_html` filter doesn't seem to be working on the `post-card-next.html` include file.

The _post-card-previous.html_ has identical code, with the word previous instead of next, and those cards on the post don't show any markup.

Any suggestions on troubleshooting this?

**Comment by biomadeira** [comment]
@rahidelvi sorry for the delay... I will have a look ;)

**Comment by rahidelvi** [comment]
No worries. Thanks for having a look.

**Comment by biomadeira** [comment]
@rahidelvi I think `page.next.content` and `page.previous.content` nomenclature is correct, but I am not understanding what you mean by "markup". Could you send me and example or print-screen of what you mean?

**Comment by Nirone7** [comment]
i understand this issue

i found the bug 'post-card-next.html'

for example https://jekyller.github.io/jasper2/the-editor 

in next post section(At the bottom of the page), you can find ``` **Getting Started** ```

refer to https://github.com/jekyll/jekyll/issues/2860

and i fixd this bug temporarily

post-card-next.html 24 line

```
-                    <p>{{ page.next.content | strip_html | truncatewords: 33, "" }}</p>
+                    <p>{{ page.next.content | markdownify | strip_html | truncatewords: 33, "" }}</p>
```

I am bad at English. So May not be natural TT

Please understand.

**Comment by rahidelvi** [comment]
@Nirone7 Thank you! That solved the problem :+1:
