### ISSUE TITLE
Confusing rss/atom feed options

### ISSUE THREAD

**Issue by mattdangerw** [jekyller/jasper2#27]
Think there is some cleanup work that could be done with the feed options provided here.

At the moment there's two toplevel feeds
 - https://github.com/myJekyll/jasper2/blob/gh-pages/atom.xml actually rss+atom from the atom.xml template file
 - https://github.com/myJekyll/jasper2/blob/gh-pages/feed.xml actually an atom feed, from jekyll-feed

Then each author/tag has its own feed.xml from the atom.xml template file. They all seem to have messed up title tags.

Not sure how to best fix this up, but thought I'd point it out! On my own fork of this project, just stripped out the atom.xml template file and used the feed provided by jekyll-feed unaltered (so no individual author/tag feeds).

Thanks for all the work on this btw!

**Comment by biomadeira** [comment]
@mattdangerw absolutely! I will have a look ;)

**Comment by biomadeira** [comment]
@mattdangerw I finally had a look at this and followed your suggestion as a simpler approach for now! See https://github.com/myJekyll/jasper2/commit/5fbba1defeb61077c4408e0d7753073106c472ea 

Thank you! 
F:)

**Comment by biomadeira** [comment]
#32

**Comment by biomadeira** [comment]
Fixed https://github.com/jekyller/jasper2/pull/33
