### ISSUE TITLE
Jekyll serve jacks up the cpu to 100% on MacOS

### ISSUE THREAD

**Issue by httpsterio** [jekyller/jasper2#29]
I don't know why but for some reason this jekyll site jacks up the CPU usage. A normal Jekyll build takes 8 seconds while on my own site (github.com/httpsterio/rautalanka) it takes under a second. I don't know if it's some gems you have installed or why, but it's almost unusable for me.

**Comment by httpsterio** [comment]
Ok solved, 
the exclude on line 45 in _config.yml gets overridden by the excludes at the bottom of the config.

node_modules was the issue that jacked everything up while building and serving the site. I'd remove the excludes from line 45 and add node_modules and .git to the exclude at the end of the config.

**Comment by biomadeira** [comment]
@httpsterio interesting stuff! Never happened to me but thanks for reporting it! See https://github.com/myJekyll/jasper2/commit/77c99b500612b5cdab24756dd39309f3afd70fce 

Cheers!
F:)
