### ISSUE TITLE
Error reading files when running on local, possibly related to 5fbba1d

### ISSUE THREAD

**Issue by kmcconnell** [jekyller/jasper2#32]
I noticed the recent commit 5fbba1d where these files were removed, but when I'm running a fresh copy of the repo locally for the first time, I'm seeing a series of `Error reading file...` messages.

```
Error reading file /Users/path/to/directory/_layouts/tag.xml: No such file or directory @ rb_sysopen - /Users/path/to/directory/_layouts/tag.xml
Error reading file /Users/path/to/directory/_layouts/author.xml: No such file or directory @ rb_sysopen - /Users/path/to/directory/_layouts/author.xml
```

Looks like tag.xml causes the error to repeat 4 times, while author.xml causes the error to repeat 7 times. I'm guessing there are still remaining references to these files somewhere?

**Comment by biomadeira** [comment]
@kmcconnell Thanks for reporting this ! Yes indeed, I forgot there were references to these files: https://github.com/jekyller/jasper2/blob/e4775cb2fb7212dd8d4d29ea6c357f6301bdb3a7/_plugins/jekyll-autgenerator.rb#L70 and https://github.com/jekyller/jasper2/blob/e4775cb2fb7212dd8d4d29ea6c357f6301bdb3a7/_plugins/jekyll-tagsgenerator.rb#L63

F:)

**Comment by biomadeira** [comment]
Fixed by @aroraakshit https://github.com/jekyller/jasper2/pull/33
