### ISSUE TITLE
Tags not working

### ISSUE THREAD

**Issue by spsharman** [jekyller/jasper2#45]
I understand that Tags don't work and have read the recommendation to upload `_site` to a repo to overcome this however I'm unable to get this to work.

Here are the steps I've tried:
- generated site to spsharman.github.io/blog - site builds but tags not working
- created a new repo (blog-pages)
- modified _config.yml to reflect /blog-pages
```
baseurl: /blog-pages/
production_url: https://spsharman.github.io/blog-pages/
source_url: https://github.com/spsharman/blog-pages/
```
- generated site `bundle exec jekyll serve`
- uploaded the _site to the /blog-pages repo
- accessed spsharman.github.io/blog-pages - pages don't build

I'm sure it's something very basic that I'm doing wrong, so looking for suggestions

Many Thanks 

Steve

**Comment by ldjb** [comment]
Hi, looking at your `[blog-pages](https://github.com/spsharman/blog-pages)` repo, it looks like it _should_ work. But clearly, trying to access https://spsharman.github.io/blog-pages/ does not work.

Have you ensured that you have enabled building the site from the `master` branch? See the [GitHub Pages documentation](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/) for information on how to do this. If GitHub returns an error message, this would be useful to know.
