### ISSUE TITLE
Authentication failed in Travis build process

### ISSUE THREAD

**Issue by bhuvnesht26** [jekyller/jasper2#47]
![travis-ci log](https://user-images.githubusercontent.com/4116233/40234011-bc2cfede-5ac2-11e8-8ae6-b2284dc9a66f.png)
@jekyller

**Comment by bd3r** [comment]
i had the same problem i fixed it by doing:
1: get your GH_TOKEN from https://github.com/settings/tokens
2: you need to run the command inside the project **directory** :
     `travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'`

example :
    `travis encrypt 'GIT_NAME="bhuvnesht26" GIT_EMAIL="bhuvnesht26@email.com" GH_TOKEN=123abc'`

* the error occured for me because i added a space by mistake in : 
    `GH_TOKEN='space'123abc`
    make sure there is none.

3: after that copy the output to your .travis.yml.

4: push to github.

i hope this helps.

**Comment by bhuvnesht26** [comment]
I had no 'space' but still it didn't work...I dont know why!! :(

**Comment by vinhpz** [comment]
I had the same problem and don't think the GH_TOKEN from Travis is working so I had to go to https://github.com/settings/tokens and created a token myself with repo permissions.

**Comment by eleazarbr** [comment]
I have the same problem:

remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/eleazarbr/eleazarbr.github.io.git/'
rake aborted!

The personal access token in GitHub says that Never used.
Also used travis encrypt as indicated, updated travis.yml and did push but it falls in

**Comment by biomadeira** [comment]
@eleazarbr make use the `DESTINATION_BRANCH` is named correctly for what you have/need/ See https://github.com/jekyller/jasper2/blob/master/Rakefile#L16

**Comment by bbagwang** [comment]
Getting Same Issue right now. I tried almost everything.
Any thing I need to check more please let me know. T.T
