### ISSUE TITLE
Remove all connections to Ghost

### ISSUE THREAD

**Issue by diomed** [jekyller/jasper2#48]
This theme is a MIT licenced project, which means you can modify however you want.
So please remove all connections to Ghost in theme itself.

It is good to keep it in readme if you want, but otherwise, why would
jekyll theme need to link to another CMS, or mention it at all? I don't see any point in that.
This should be a proper port, without mentioning other CMS

**Comment by biomadeira** [comment]
@diomed Although I see your point, I think it wouldn't be fair not to mention [Ghost](https://github.com/tryghost) and the [Casper](https://github.com/tryghost/casper) theme folks. This Jekyll theme wouldn't exist if it wasn't for them to developing and making it available in the first place...
