### ISSUE TITLE
Pages not found on blog post

### ISSUE THREAD

**Issue by ishu3101** [jekyller/jasper2#52]
I have forked the theme and deployed it as a project using gitlab pages like http://username.gitlab.io/jasper2. Now when I click on any link to open the blog post, I'm getting 404 Page not found error message.

I noticed that when I append .html to the end of the url for the blog post like for eg: http://username.gitlab.io/jasper2/welcome.html the blog post is being displayed but if I remove the html it is display the 404 Page not found error message.

Does anyone have any ideas on how to fix that?

**Comment by noahzhy** [comment]
You just need to change the line 36
>permalink: /:title

to 

>permalink: /:title.html
