### ISSUE TITLE
Incorrect formatting of markdown on internet explorer

### ISSUE THREAD

**Issue by wesleyhutchinson** [jekyller/jasper2#58]
formatting on internet explorer causes text to be one continuous line and is hidden by left and right hand sides of the screen on 'post' view

**Comment by wesleyhutchinson** [comment]
PR regarding above added.

**Comment by biomadeira** [comment]
Fix https://github.com/jekyller/jasper2/pull/56/commits/994f56a61b978c43b1e1c071bdc2746a3a22ae69 and merge https://github.com/jekyller/jasper2/pull/56
