### ISSUE TITLE
Code blocks are truncated in Mobile

### ISSUE THREAD

**Issue by karthikchintala1** [jekyller/jasper2#61]
I recently installed jasper theme for my blog. I found that the code blocks are being truncated when viewing in my mobile. So, I cannot scroll to the right/left in the mobile for code blocks.

A sample page of my blog
[generating-sequence-numbers-in-linq-query](https://coderethinked.com/generating-sequence-numbers-in-linq-query)

### Steps to reproduce:

1. navigate to above url
2. Press F12 for developer tools 
3. Press `Ctrl` + `Shift` + `M` (for toggling device tollbar) - This is for chrome browser.

![image](https://user-images.githubusercontent.com/16499209/44321654-e3c8b080-a466-11e8-859c-c1254d891e64.png)

**Comment by LorenzoLeonardini** [comment]
My temporary fix is to add

```html
<style>
    .highlighter-rouge, .highlight, code {
        width: 100%;
    }
</style>
```

at the bottom of `_includes/head.html`

**Comment by spirosbax** [comment]
Pull request #117 fixes it for me!
