### ISSUE TITLE
RSS feed for author isn't generated

### ISSUE THREAD

**Issue by Xartos** [jekyller/jasper2#62]
In the page for a specific author there's a link to the RSS feed for the author, although there is never generated any feed.xml to that location.

The file is suppose to reside in `{{ site.url }}{{ site.baseurl }}author/{{ page.author }}/feed.xml` (from `_layouts/author.html`)

**Comment by biomadeira** [comment]
@Xartos I though we were generating these with jekyll-feed, but it seems to only work for the blog posts... I will have a look to add these for authors and tags!
