### ISSUE TITLE
Author & Tags redirect to 404

### ISSUE THREAD

**Issue by techlanka** [jekyller/jasper2#64]
Author & Tags are not working, they redirects to 404 not found page. Pls help https://github.com/techlanka/techlanka

**Comment by techlanka** [comment]
> Author & Tags are not working, they redirects to 404 not found page. Pls help https://github.com/techlanka/techlanka

please need assistance asap.:(

**Comment by biomadeira** [comment]
@techlanka be sure to follow the notes on https://github.com/jekyller/jasper2#deployment

**Comment by techlanka** [comment]
I got a fix via forestry.io

**Comment by estevanmaito** [comment]
Hi.

I'm using Netlify to deploy my blog to https://blog.unna.tech and I'm having the same problem, author and tag pages result in 404. You can see it by following the author link at the bottom of this post https://blog.unna.tech/i-have-a-dream

I followed the 3rd option from deployment tutorial, with no success. Running `bundle exec jekyll serve` locally doesn't generate neither author nor tag pages

The code is here: https://github.com/unna-tech/blog

This is my Netlify build config: ![netlify-deploy](https://user-images.githubusercontent.com/8527573/51734311-50298a80-206b-11e9-9f43-496bd2effad8.png)

**Comment by techlanka** [comment]
> Hi.
> 
> I'm using Netlify to deploy my blog to https://blog.unna.tech and I'm having the same problem, author and tag pages result in 404. You can see it by following the author link at the bottom of this post https://blog.unna.tech/i-have-a-dream
> 
> I followed the 3rd option from deployment tutorial, with no success. Running `bundle exec jekyll serve` locally doesn't generate neither author nor tag pages
> 
> The code is here: https://github.com/unna-tech/blog
> 
> This is my Netlify build config: ![netlify-deploy](https://user-images.githubusercontent.com/8527573/51734311-50298a80-206b-11e9-9f43-496bd2effad8.png)

Make sure your baseurl is as follows,

baseurl: /

**Comment by estevanmaito** [comment]
@techlanka that's exactly what it is, if you look in my _config.yml

**Comment by techlanka** [comment]
> It worked after I've made some changes to the Gemfile.
> 
> This was the first time I've installed Jekyll in Windows, so I've followed their tutorial on installing to this OS. At first my Gemfile looked like this:
> 
> ```
> source "https://rubygems.org"
> 
> gem "github-pages", group: :jekyll_plugins
> gem "rake", "~> 12.3.1"
> 
> # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
> gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
> 
> # Performance-booster for watching directories on Windows
> gem "wdm", "~> 0.1.0" if Gem.win_platform?
> ```
> For some reason that I don't remember, I had to change the github-pages gem. The solution I've found was to mix the styles of the Jekyll recomendation for Windows with this theme's Gemfile, like below:
> 
> ```
> source "https://rubygems.org"
> 
> gem "jekyll", "~> 3.7.4"
> gem "github-pages", "~> 192"
> gem "rake", "~> 12.3.1"
> 
> # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
> gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
> 
> # Performance-booster for watching directories on Windows
> gem "wdm", "~> 0.1.0" if Gem.win_platform?
> ```
> It's now working and generating the tags and authors pages correctly.

Roger that!!

**Comment by JobiJoba** [comment]
Hey, 

I'm having the same issue but whatever I try, i'm not able to fix it ... 
So right now I"m using Travis to build and deploy which is working well, the page author and tag are well generated but If i try to reach them i get a 404. 

Locally no issue ... only on github pages (https://github.com/JobiJoba/jobijoba.github.io) 

Any idea ?

**Comment by TheoKanning** [comment]
This happens because the `github-pages` plugin sets the plugins directory to a random string. 
https://github.com/jekyll/jekyll/issues/5265#issuecomment-241267253

I'm using jasper2 as a remote theme, and I had to remove version 206 of the `github-pages` plugin and add some of its dependencies manually.

` source "https://rubygems.org"
   
  gem "jekyll", "~> 3.8.7", group: :jekyll_plugins                                                
  group :jekyll_plugins do                                                                        
    gem "jekyll-paginate", "~> 1.1.0"                                                             
    gem "jekyll-remote-theme", "~> 0.4.1"                                                         
  end                                    
  gem "slugify", "~> 1.0"
`

**Comment by Zhanes** [comment]
I tried a mix of everything commented here. And for me it's the same, it generate all the site except the authors & the tags. Any idea how to fix it?

Here my Gemfile:

`
source "https://rubygems.org"

gem "rake", "~> 12.3.1"
gem "slugify", "~> 1.0"

gem "jekyll", "~> 3.9.0", group: :jekyll_plugins
group :jekyll_plugins do
  gem "jekyll-paginate", "~> 1.1.0"
  gem "jekyll-remote-theme", "~> 0.4.1"
  gem 'jekyll-tagsgenerator', '~> 0.0.2'
  gem 'jekyll-feed', '~> 0.15.1'
  gem 'kramdown-parser-gfm', '~> 1.1'
end
gem "slugify", "~> 1.0"
gem "github-pages", "~> 209"`
