### ISSUE TITLE
Creating a new dropdown menu.

### ISSUE THREAD

**Issue by techlanka** [jekyller/jasper2#66]
Help me to create a simple 3 column dropdown menu on top of the template.

**Comment by cdrrazan** [comment]
I have a tried few dropdown styles in this theme around but none of them seem to work as expected in normal way. I tried with creating data.yml like structure to rewriting navigation.html liquid tags but it won't help. Any recommendation or upgrades here, author?

**Comment by biomadeira** [comment]
@techlanka Let me know if you still need help with this!
