### ISSUE TITLE
Site Deployment Problem

### ISSUE THREAD

**Issue by cdrrazan** [jekyller/jasper2#67]
I tried deploying the theme by ```bundle exec jekyll build``` and uploading the generated pages to the github. However if i use CNAME, the site breaks down. 

Also i noticed in local environment if i use baseurl: '/' the site deploys at https://localhost:4000// and if i just leave the field empty the site would just render html and not the CSS files. Can anybody suggest best way to use CNAME or baseurl here?

**Comment by cdrrazan** [comment]
I did some tweaks based on the previous closed issue although they weren't related completely. This is wonderful theme by the way. :+1:

**Comment by rcosteira79** [comment]
Hi! I'm having the same problem. How did you fix it? Thank you!
