### ISSUE TITLE
Changing or adding a font

### ISSUE THREAD

**Issue by techlanka** [jekyller/jasper2#68]
Guide me to change or add a font to the repo.plsss

**Comment by diomed** [comment]
well, wherever there is Georgia, you can replace it with some other font:
https://github.com/jekyller/jasper2/blob/master/assets/css/screen.css

if you're importing from google fonts, on top of css file put for example:

` @import url('https://fonts.googleapis.com/css?family=Muli');`

(You probably know this already, I'm writing answer for future reference.)

**Comment by chamyeongseop** [comment]
@diomed Thanks for your advice.
But It is hard to add additional font for me... but i solved it. 

I want to write additional information not to spend your time.

1. Please check that you have installed npm and gulp. My troubles came from two causes.

2. As soon as you installed npm and gulp, you can see that gulp is generating on your personal theme folder.

3. Enter /assets/css/screen.css and Write import address on top of scripts. 
ex) @import url('https://fonts.googleapis.com/css?family=Open+Sans'); 

4. Replace Georiga, serif; into your favorite font type (ex) Georgia, serif -> 'Nanum Gothic', sans-serif

I hope my experience will help you.
