### ISSUE TITLE
Adding a Page listing all authors

### ISSUE THREAD

**Issue by techlanka** [jekyller/jasper2#70]
please give me a suggestion for adding a page to list all the blog authors in github pages!

**Comment by techlanka** [comment]
@biomadeira Got any idea?

**Comment by techlanka** [comment]
https://medium.com/aspirethemes/how-to-create-an-authors-page-in-your-ghost-theme-256ee898e5a2
Refer to this note and help me fix this.

**Comment by n-alex-white** [comment]
Is it not as simple as following the advice in the introductory tutorial for Jekyll under ‘collections’?

https://jekyllrb.com/docs/step-by-step/09-collections/

The blog authors are all in _data/authors.yml, so you just create an authors jekyll page which reads the data and produces whatever kind of list you want?

**Comment by biomadeira** [comment]
@techlanka Let me know if you still need help with this!
