### ISSUE TITLE
This theme is not compatible with Chinese

### ISSUE THREAD

**Issue by wanyt** [jekyller/jasper2#72]
I writing post with Chinese, but there has something wrong.

<img width="1627" alt="3320420f3044457de5bdf52e44abbee8" src="https://user-images.githubusercontent.com/12974087/47777232-44118380-dd2f-11e8-9c0a-f5a65f7b6292.png">

<img width="1627" alt="dcb8a18548479c8c85c75e97477ed31a" src="https://user-images.githubusercontent.com/12974087/47777270-555a9000-dd2f-11e8-87e4-be8cc12c6723.png">

**Comment by techlanka** [comment]
Make changes to the _includes. postcard.html as below.

>                     **<p>{{ post.content | strip_html | truncatewords: 23, "" }}</p>**

**Comment by wanyt** [comment]
It didn't work out after the change.
<img width="1386" alt="590f6662-19fe-4e8c-8c54-63e49666f670" src="https://user-images.githubusercontent.com/12974087/47788477-d1af9c00-dd4c-11e8-9784-66eca4613259.png">
