### ISSUE TITLE
How to create a new tag

### ISSUE THREAD

**Issue by wanyt** [jekyller/jasper2#73]

**Comment by techlanka** [comment]
please elaborate your issue.

**Comment by wanyt** [comment]
I want to know how to show this:
<img width="1322" alt="a47bd10e-f403-4156-8879-759118cfe040" src="https://user-images.githubusercontent.com/12974087/47964517-3e40d880-e076-11e8-8ac7-86498a019abc.png">

**Comment by techlanka** [comment]
its simple as that, add more than one post for the tag u want to make it visible here. And try it will show up. Unless you made or delete any html file under includes named post-card.

**Comment by wanyt** [comment]
Thank you
