### ISSUE TITLE
When I deploy, baseURL will become http://localhost:4000/.

### ISSUE THREAD

**Issue by wanyt** [jekyller/jasper2#74]
This is my [blog](https://wanyt.github.io/Flutter-navigator-1) sit. When I click on this text in the bottom of this page:
![59478088-d6b2-4e5e-82ef-2a8dabaa2887](https://user-images.githubusercontent.com/12974087/48423033-cd4aa080-e79a-11e8-8157-823ffa19ce32.png)
Chrome will navigate to localhost:4000:
![a979e330ebaf4e7b8f2f4b8541394d45](https://user-images.githubusercontent.com/12974087/48422811-62996500-e79a-11e8-9be2-6a6798f6a3d9.png)
I want to know how to fix it.

**Comment by manideep2510** [comment]
Can you tell me how you fixed it?
