### ISSUE TITLE
Normal GitHub pages deployment

### ISSUE THREAD

**Issue by abpaudel** [jekyller/jasper2#80]
As per the readme, there are problems with normal github pages deployment with this theme because of issues with plugins. However, I just tried deploying a github page without any visible issue. Can someone clarify what issues are there with this method of deployment?

**Comment by wtho** [comment]
When you add posts, it is not enough to just create a new `.md` file, but to use all the features of the blog-template, such as cross-referenced tags, the plugins have to be executed and the changes committed.

If GitHub would enable plugins on their Jekyll Engine, it would do it for you on startup, but in the current situation you have to run it on your local machine or some CI server and commit & push the generated changes.

**Comment by michalzobec** [comment]
> If GitHub would enable plugins on their Jekyll Engine, it would do it for you on startup, but in the current situation you have to run it on your local machine or some CI server and commit & push the generated changes.

so it is not possible enable plugins on GitHub?
you cannot create fully compatible theme for GitHub Page?

**Comment by maximousblk** [comment]
If it is not possible to do the normal deployment then a video or even a write up about the option 2 will be super helpful for people like me who are new to these things.

**Comment by wtho** [comment]
@michalzobec GitHub only has the base plugins enabled. If you build a theme without pagenation, tags, ..., then it will work on GitHub pages out of the box without generating these each time by hand.

@maximousblk It would definitely work with GitHub Actions, but I do not know if anyone set it up before, so some fiddling around and testing might be required. But probably you can just migrate most of the commands from the TravisCI build.

**Comment by maximousblk** [comment]
@wtho other themes like pintereso (https://github.com/wowthemesnet/template-pintereso-bootstrap-jekyll) do the pagination and tags but still work with "normal" deployment.

I think we can borrow some things from other themes cuz this is a good theme which I need right now and don't have access to my computer (not saying you should do this for me).

**Comment by abpaudel** [comment]
@maximousblk I've been running the theme by omitting external plugin features. I too am planning integrate tags and other features by referring to other themes that does so without external plugins.

**Comment by maximousblk** [comment]
Meanwhile, can someone help me set it up using netlify? The instructions don't seem clear.

**Comment by wtho** [comment]
I think this should help you figure it out:
* A [list with plugins](https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#plugins) *always* enabled by GitHub Pages (read the whole documentation to learn more about gh-pages)
* A [list with plugins supported](https://pages.github.com/versions/) by GitHub Pages
* A [GitHub Action to run Jekyll](https://github.com/marketplace/actions/jekyll-action) to do the compilation and commiting of built files to be able to only update `.md` files

**Comment by maximousblk** [comment]
What are the plugins not supported by github pages that is used in this theme?

**Comment by wtho** [comment]
I'm also just some guy who once tried out this theme. Please try to research a little more before you ask for every small detail.

In the top of the jasper2 README in the section **Getting Started** it says
> Important: For security reasons, Github does not allow plugins (under _plugins/) when deploying with Github Pages.

Having a look at [the plugins directory `/_plugins/](https://github.com/jekyller/jasper2/tree/master/_plugins), you can immediately see, that there are custom plugins not supported natively by GHP.

**Comment by maximousblk** [comment]
Let's not heat up.

Sorry for being naive but I was just thinking about using JavaScript alternatives for the unsupported plugins. I mean, capitalisation can be done with js, right?

**Comment by wtho** [comment]
Haha don't worry, I'm glad to help!
Just clarifying.

Of course you can use JS (I assume you mean client-side), but that would defeat the purpose of Jekyll and its strength to fully render a website on the server side and being independent of JS.

I would recommend to setup GitHub Actions, it might take a day to get into it and set it up, but then you're free to use any additional Jekyll plugins.

**Comment by maximousblk** [comment]
That's the problem. GitHub actions is not working for me

**Comment by michalzobec** [comment]
> @michalzobec GitHub only has the base plugins enabled. If you build a theme without pagenation, tags, ..., then it will work on GitHub pages out of the box without generating these each time by hand.

where is a little problem: I use GitHub only, I am not have any build tool (except Visual Studio).

**Comment by biomadeira** [comment]
@abpaudel @michalzobec @maximousblk @wtho  The latest developments with GitHub Actions make it work fine. I have added this basic [workflow](https://github.com/jekyller/jasper2/blob/master/.github/workflows/jekyll_build.yml).
I have now stopped building with TravisCI and then pushing to gh-pages branch, as the workflow (using this [action](https://github.com/marketplace/actions/jekyll-actions) does everything out of the box for us. 
Read more here: https://jekyllrb.com/docs/continuous-integration/github-actions/
