### ISSUE TITLE
How to make post preview have a uniform layout in posts feed

### ISSUE THREAD

**Issue by rnehra01** [jekyller/jasper2#82]
In the post feed at the home page, some posts have a horizontal layout while some have a vertical layout, how can I make all posts to have a horizontal layout? I tried looking at the HTML but it looks same to me for all of them.

**Comment by biomadeira** [comment]
@rnehra01 I think this a feature of the theme as designed by the folks at Ghost.org. Something to do with the grid layout...  let me know if you still need help with this, so I could try having a look.
