### ISSUE TITLE
Form and button style error

### ISSUE THREAD

**Issue by quyleanh** [jekyller/jasper2#86]
As I can see all the form and many elements inside have style error. Could you please take a look?
https://jekyller.github.io/jasper2/a-full-and-comprehensive-style-test

**Comment by biomadeira** [comment]
@quyleanh  They look good for me, but let me know if this is still an issue for you!

**Comment by quyleanh** [comment]
Actually I don't know if this is OK. Could you please take a look? Thank you.

![image](https://user-images.githubusercontent.com/9365035/118264599-1dc52500-b4e2-11eb-9a73-259e5a8f0cdf.png)

**Comment by biomadeira** [comment]
@quyleanh Ohh I see what you mean now. The placement of the boxes and labels is weird indeed... this was copied as it was based on the Casper theme by the Ghost folks. They are now running version 4 of the theme but it still looks like that 😄  
See https://demo.ghost.io/style-test/

**Comment by quyleanh** [comment]
Thank you for your kind reply.
I think the default one has no custom CSS. Understand now.
