### ISSUE TITLE
Works fine on local but css does not rendered on github page

### ISSUE THREAD

**Issue by yifan97** [jekyller/jasper2#87]
When I deploy this to github page there is no styling. 
I have tried changed to baseurl to my github page sub directory.

**Comment by chamyeongseop** [comment]
Hello! I had a similar problem like you. Could you exchange baseurl context into "/ "? As you know, There is relational comments.  i solved when i write only / on baseurl in _config.yml file.

**Comment by godsman-yang** [comment]
In that case, baseurl: / then site style is good, but getting favicon.png has error.
so, I add url: https://{username}.github.io

--- Error --
GET https://{username}.github.ioassets/images/favicon.png net::ERR_NAME_NOT_RESOLVED 
-> there is no '/' between https://{username}.github.io(site.url) and assets/images/favicon.png(favicon)

**Comment by maimanuel** [comment]
what helped me was to use a leading '/' before the assets, for example:

```yml
favicon:  /assets/images/favicon.png
```
