### ISSUE TITLE
The About page style is broken.

### ISSUE THREAD

**Issue by godsman-yang** [jekyller/jasper2#91]
baseurl: /
url: https://{username}.github.io/

The about page style is broken because that page tries to find images from about/assets/images.
The Images related to about are located in the assets/images folder.

**Comment by Jetroid** [comment]
{{ site.baseurl }} is entirely unnecessary in a user site (ie one where jasper2 can be found at https://{username}.github.io/ )

I suggest doing this:

in _config.yml, set:

```
baseurl: ""
```
then run this script:
```
find /path/to/jasper2/ -type f -exec sed -i 's/{{ site.baseurl }}/\//g' {} \;
```

... which replaces all instances of `{{ site.baseurl }}` with `/`, so links are relative links.
